### ISSUE TITLE
Leading underscore at _checked-function?

### ISSUE THREAD

**Issue by der-lukas** [airesvsg/acf-to-rest-api-example#2]
Hey! This is not an issue, but a question out of interest:

You defined the function _checked() in functions.php and use it multiple times in index.php.
But sometimes you use it with leading underscore and sometimes without.

I didn't even know you could do that and wanted to ask why you did it! :)

First thing I found was this [stackoverflow-discussion](http://stackoverflow.com/questions/663350/whats-the-deal-with-a-leading-underscore-in-php-class-methods) where they said it's for private methods and shouldn't be used... 

Don't want to discuss here - just interested in why you used it and why once with and once without the underscore! :)

**Comment by airesvsg** [comment]
Hi @der-lukas,
The difference of my function is that it checks the values in the array ( [functions.php#L24](https://github.com/airesvsg/acf-to-rest-api-example/blob/master/functions.php#L24) ), if is string it uses the default function, for this reason I used the underscore.

I also use the underscore in private methods in OOP.

**Comment by der-lukas** [comment]
Thanks for clearing this up! ;)

**Comment by airesvsg** [comment]
:smile::+1:
