### ISSUE TITLE
PUT  request  not working using Oauth2 and acf Pro

### ISSUE THREAD

**Issue by rolandalla** [airesvsg/acf-to-rest-api-example#5]
Hello ,I'm having problems using PUT methods to update the option fields  , my function is like below : 
![image](https://cloud.githubusercontent.com/assets/5981015/15430794/31aefa7c-1ea7-11e6-8e5b-47ff6179da1f.png)

I'm getting this error:
 [code] => cant_update_item
    [message] => Cannot update item
    [data] => stdClass Object
        (
            [status] => 500
        )

I used GET  Method and everything  is OK , All other API call are all right .
Regards.

**Comment by airesvsg** [comment]
Hi @roladn,
please, read the documentation about authentication
http://v2.wp-api.org/guide/authentication/
Thanks

**Comment by rolandalla** [comment]
Thanks For Reply , The authentication is all right ,I'm authenticated  but the only one problem i have  is to update the ACF options field.
Thanks

**Comment by rolandalla** [comment]
![image](https://cloud.githubusercontent.com/assets/5981015/15465442/d469e770-20d4-11e6-8f08-9d7986dc6943.png)

I'm testing this using postman and nothing is happening.

Something is not correct , or I'm not sending the correct parameter to the PUT request .

Please check this

**Comment by airesvsg** [comment]
Hi @roladn,
what's the version of your ACF?
Thanks

**Comment by rolandalla** [comment]
Hi @airesvsg  . 
Version 5.3.8.1  Pro Version
Thanks

**Comment by airesvsg** [comment]
Hi @roladn,
please put this snippet in your **functions.php**

``` PHP
add_filter( 'acf/location/rule_match/options_page', function(){
    return true;
} );

add_filter( 'acf/rest_api/option/prepare_item', function( $item ){
    if ( isset( $item['id'] ) ) {
        $item['id'] = 'options';
    }

    return $item;
});
```

Thanks

**Comment by rolandalla** [comment]
Thank you , Is all right now . Thanks for your work 
Best regards

**Comment by rolandalla** [comment]
Hello , everything is ok with this solution , but there is another bug coming by this functions .\
The acf field for options now are showed in every post type . 
![image](https://cloud.githubusercontent.com/assets/5981015/16682021/856266e6-44f8-11e6-8b17-1c40e8c90b57.png)

This must be only at theme options 

Thank you

**Comment by rolandalla** [comment]
As i checked this function :
add_filter( 'acf/location/rule_match/options_page', function(){
    return true;
} );
is returning true in every post  type

**Comment by ileafsolutions** [comment]
Hi, Could you help me in editing a notes field of acf. Here is the response which I have when called this http://test.localhost/wp-json/acf/v2/user/279 using the method GET
{
"acf": {
"notes": [
{
"note": "test test",
"user_id": "3",
"col1": null,
"user_name": "siteadmin",
"col2": null,
"created_at": "08/05/2016 09:08:55 am",
"col3": null,
"modified": "08/05/2016 09:09:39 am"
},
{
"note": "test2 test2",
"user_id": "3",
"col1": null,
"user_name": "siteadmin",
"col2": null,
"created_at": "08/05/2016 09:08:55 am",
"col3": null,
"modified": "08/05/2016 09:09:40 am"
}
]

I would like to add another notes. I tried with PUT method and it says 
{
"code": "cant_update_item",
"message": "Cannot update item",
"data": {
"status": 500
}
}

I have tried via postman.Its would be great if you could help me on this.

**Comment by rolandalla** [comment]
Hello , the problem is that you must be authenticated . Please check the
wordpress   Rest Api  documentation and do the authentication with one
method .. and tray again the PUT

**Comment by ileafsolutions** [comment]
Yes, I tried with Basic Auth authentication

**Comment by rolandalla** [comment]
`add_filter( 'acf/location/rule_match/options_page', function(){
    return true;
} );

add_filter( 'acf/rest_api/option/prepare_item', function( $item ){
    if ( isset( $item['id'] ) ) {
        $item['id'] = 'options';
    }

```
return $item;
```

}); `

Did you ad this snippet at your function.php

**Comment by ileafsolutions** [comment]
As I need to edit on my user custom field I provided like this in function.php 
add_filter( 'acf/location/rule_match/user', function(){
    return true;
} );
But nothing worked out
